CREATE TABLE INPUT_SENSORS(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	greenHouseId INTEGER NOT NULL,
	airHum FLOAT NOT NULL,
	airTemp FLOAT NOT NULL,
	lightQuantity FLOAT NOT NULL,
	terrainHum FLOAT NOT NULL,
	isTankEmpty INTEGER NOT NULL,
	timeStamp DATETIME NOT NULL
)