CREATE TABLE IF NOT EXISTS OUTPUT_ACTUATORS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    greenHouseId INTEGER NOT NULL,
    irrigationPump INTEGER NOT NULL,
    UVLight INTEGER NOT NULL,
    ventilation INTEGER NOT NULL,
    timeStamp DATETIME NOT NULL
)